<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>fbd09d6b-e9e9-48fe-877f-f200475bfc9b</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MockMe.Repository\MockMe.Repository.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Properties\ServiceDependencies\" />
	</ItemGroup>

</Project>
